### ISSUE TITLE
java.lang.NoSuchMethodError: No static method zzb

### ISSUE THREAD

**Issue by jqn** [pusher/pusher-websocket-android#32]
I keep getting this error when trying to implement FCM, perhaps someone can help me figure out what the problem is:

```
03-10 10:06:28.883 29257-29257/com.dlinkapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.dlinkapp, PID: 29257
                                                              java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzaa; or its super classes (declaration of 'com.google.android.gms.common.internal.zzaa' appears in /data/data/com.dlinkapp/files/instant-run/dex/slice-com.google.android.gms-play-services-basement-10.2.0_8eb7517ae6cd13d6f28eb8730dd89fb5a9522c88-classes.dex)
                                                                  at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
                                                                  at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                  at android.app.ActivityThread.installProvider(ActivityThread.java:6767)
                                                                  at android.app.ActivityThread.installContentProviders(ActivityThread.java:6362)
                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6302)
                                                                  at android.app.ActivityThread.access$1800(ActivityThread.java:222)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:158)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)```

**Comment by YoonjaeYoo** [comment]
See this http://stackoverflow.com/questions/38202644/no-static-method-zzur-in-firebase-when-i-try-to-use-analytics-with-notificatio

**Comment by zmarkan** [comment]
Thanks, that's correct ^^

**Comment by jqn** [comment]
Thanks @YoonjaeYoo - the fix from StackOverflow didn't fix my problem. I'm using React Native and adding this to my app/build.gradle seem to have fixed the issue:
```
    compile "com.google.android.gms:play-services-base:10.2.0"
    compile 'com.google.android.gms:play-services-location:10.2.0'
    compile 'com.google.android.gms:play-services-maps:10.2.0'
```

**Comment by pencilcheck** [comment]
Still keep getting this error somehow after setting all version to be the same.

**Comment by pencilcheck** [comment]
This works for me
```
  compile 'com.google.android.gms:play-services:+'
  compile 'com.google.firebase:firebase-core:+'
```

**Comment by apurvaaggarwal** [comment]
update all library versions and gms version as well . It will definitely work. Make sure all google services library you are using must be of same version
