### ISSUE TITLE
NullPointerException when `subscribe` invoked without `PushNotificationRegistrationListener`.

### ISSUE THREAD

**Issue by YoonjaeYoo** [pusher/pusher-websocket-android#35]
I've done like:
```
pusher.nativePusher().subscribe("user_123");
```
then (when push notification registration failed):
```
E/UncaughtException: java.lang.NullPointerException: Attempt to invoke interface method 'void com.pusher.android.notifications.interests.InterestSubscriptionChangeListener.onSubscriptionChangeFailed(int, java.lang.String)' on a null object reference
                                                                         at com.pusher.android.notifications.PushNotificationRegistration.onFailedRegistration(PushNotificationRegistration.java:194)
                                                                         at com.pusher.android.notifications.tokens.RegistrationListenerStack.onFailedRegistration(RegistrationListenerStack.java:39)
                                                                         at com.pusher.android.notifications.tokens.TokenUploadHandler.onFailure(TokenUploadHandler.java:54)
                                                                         at com.pusher.android.notifications.tokens.TokenUploadHandler.onFailure(TokenUploadHandler.java:44)
                                                                         at com.loopj.android.http.JsonHttpResponseHandler$2$1.run(JsonHttpResponseHandler.java:203)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

After digging, I realized that the bug lies in `PushNotificationRegistration.java`:
```
    @Override
    public void onFailedRegistration(int statusCode, String reason) {
        for (Iterator<Subscription> iterator = pendingSubscriptions.iterator(); iterator.hasNext();){
            Subscription subscription = iterator.next();
            subscription.getListener().onSubscriptionChangeFailed(statusCode, reason);
            iterator.remove();
        }
    }
```
`getListener()` is not checked upon whether it is `null`.
Please fix this. 
Thank you.

**Comment by zmarkan** [comment]
Gotcha, thanks.

**Comment by zmarkan** [comment]
Fixed in: https://github.com/pusher/pusher-websocket-android/pull/37

**Comment by wdifruscio** [comment]
This just saved me on a work project! ❤️
