### ISSUE TITLE
GCMRegistrationIntentService NullPointerException

### ISSUE THREAD

**Issue by vyacheslav-volkov** [pusher/pusher-websocket-android#43]
Hi there,
I checked google play console logs and I see this exception, you need to handle null intent.

https://stackoverflow.com/questions/37960917/android-intentservice-triggered-with-null-intent
https://stackoverflow.com/questions/22309582/intentservices-onhandleintentintent-gets-null-argument

java.lang.NullPointerException: 
  at com.pusher.android.notifications.gcm.GCMRegistrationIntentService.onHandleIntent(GCMRegistrationIntentService.java:29)
  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:158)
  at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by zmarkan** [comment]
Thank you, I'll look into it.

I'll let you know when I've resolved it.

**Comment by kn100** [comment]
Closing due to age
