### ISSUE TITLE
FCMMessagingService is not registered in manifest

### ISSUE THREAD

**Issue by sagarmaiyad** [pusher/pusher-websocket-android#45]
### What is the issue?
Hi, when i am using custom messaging service, it gives me crash report for that.

below is the code for custom messaging service.

     class CustomFCMMessagingService : FirebaseMessagingService() {

    override fun onMessageReceived(remoteMessage: RemoteMessage?) {
        super.onMessageReceived(remoteMessage)

        Log.e(CustomFCMMessagingService::class.java.simpleName, "Message received via custom handler!")
  
    }

  
    }

below is AndroidManifest.xml:

        <service
            android:name=".listeners.MyFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>

        

        <service
            android:name="com.pusher.android.notifications.fcm.FCMInstanceIDService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
... 

### Is it a crash report? Submit stack traces or anything that you think would help
Caused by: com.pusher.android.notifications.ManifestValidator$InvalidManifestException: com.pusher.android.notifications.fcm.FCMMessagingService is not registered in your AndroidManifest.xml
                                                              at com.pusher.android.notifications.ManifestValidator.checkServicesInManifest(ManifestValidator.java:44)
                                                              at com.pusher.android.notifications.ManifestValidator.validateFCM(ManifestValidator.java:38)
                                                              at com.pusher.android.notifications.PushNotificationRegistration.registerFCM(PushNotificationRegistration.java:114)
                                                              at com.pusher.android.notifications.PushNotificationRegistration.registerFCM(PushNotificationRegistration.java:130)
                                                              at com.takton.activity.activityView.MainMenuActivity.onCreate(MainMenuActivity.kt:49)
...

### Any improvements you suggest

...

---- 

CC @pusher/mobile

**Comment by zmarkan** [comment]
Hi there,

what version of the library are you using? This throw was removed in `0.6.0` (the latest version).

**Comment by sagarmaiyad** [comment]
@zmarkan thanks.. its working now..
